### ISSUE TITLE
Outdated installation instructions

### ISSUE THREAD

**Issue by Paebbels** [asciidoc-py/asciidoc-py2#114] opened 2017-08-17 06:57 UTC
The installation instructions reference a google code Mercurial repository.

**Comment by PackElend** [comment] 2017-08-24 05:48
please update, I had to download it manually to get it to work

**Comment by elextr** [comment] 2017-08-24 06:18
All the documentation is on the gh-pages branch, feel free to propose a pull request.

**Comment by Paebbels** [comment] 2017-08-24 06:32
The idea of open source, free documentation and pull requests should not lead to a responsibility inversion as you propose. It's not the duty of users to provide major parts of the documentation for a project! Otherwise one would call them contributors or authors.

Yes, it's nice if users find bugs and typos in the documentation, but demanding a rewrite on installation instructions is a step too much.

**Comment by elextr** [comment] 2017-08-24 06:53
@Paebbels nobody is "demanding" anything, but if nobody contributes to a volunteer project then nothing will happen.

Asciidoc Python is effectively in "end of life" phase, particularly the Python 2 version, as end of Python 2 is in 2020.  There is no development happening on this version of Asciidoc, at the moment all new development is on the [Asciidoctor](https://github.com/asciidoctor/asciidoctor) implementation, so there is nobody to be "responsible", inverted or not.  The only changes that happen are those people contribute.

**Comment by mojavelinux** [comment] 2017-08-24 08:37
The problem is, no one knows how to build the website and it's really a convoluted system. If someone can figure out how to build it locally, it's trivial to get Travis to push the result to GitHub Pages. The one requirement is that the files need to be built to an output directory since that is how Travis knows what to publish.

**Comment by elextr** [comment] 2017-08-24 11:07
@mojavelinux having discovered the gh-pages branch I was hoping that "all" that was needed was for the changed `.txt` and the `.html` file built from it to be merged into the gh-pages branch, but I've never used gh-pages.

**Comment by mojavelinux** [comment] 2017-09-03 21:56
Sure, until the next time an update is needed. Since this is such a broken window, I suppose an exception is warranted for this one.

If someone can figure out how to build the website, we can easily get Travis to do it. Otherwise, we have to make manual updates.

**Comment by mojavelinux** [comment] 2017-09-03 22:26
The page has been updated. http://asciidoc.org/INSTALL.html

**Closed as completed** 2017-09-03 22:26 UTC

**Comment by erikbgithub** [comment] 2017-09-04 15:32
Well, at least as maintainer one should end the project by adding a corresponding notice in the README and/or Documentation start page.

Btw really disappointing that development only continues in Ruby.

**Comment by elextr** [comment] 2017-09-04 23:12
@erikbgithub Well, the source will keep working until the end of Python 2.  The Ruby version allows github to still render asciidoc, otherwise that capability may have been lost.

Somebody made an attempt to create a [Python 3](https://github.com/asciidoc/asciidoc3) version, but seem to have become stuck with the task of making all the regression tests pass.  If you want a Python version to continue you can contribute to that.

To be clear, this is open source, if you want a project to continue you need to contribute.

**Comment by erikbgithub** [comment] 2017-09-05 07:33
@elextr All I'm saying is this: if you don't continue as the core maintainer, you should make that readable at the front page, not in some issue somewhere in the background. It's a very small thing to add that one sentence to your README.

PS: You can be sure that I provide changes to open source projects if I can afford to invest the time, probably same as you. There are at least 5 FOSS projects I would be willing to work full time on if someone would be willing to take care of my bills, for instance. ;)
